# Generated by Django 3.2 on 2021-08-11 09:48

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ipam', '0046_set_vlangroup_scope_types'),
    ]

    operations = [
        migrations.CreateModel(
            name='VirtualCircuit',
            fields=[
                ('created', models.DateField(auto_now_add=True, null=True)),
                ('last_updated', models.DateTimeField(auto_now=True, null=True)),
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('vcid', models.BigIntegerField(default='', validators=[django.core.validators.MaxValueValidator(4294967295), django.core.validators.MinValueValidator(1)])),
                ('name', models.CharField(max_length=64)),
                ('status', models.CharField(default='pending-configuration', max_length=30)),
                ('context', models.CharField(blank=True, max_length=100)),
                ('description', models.CharField(blank=True, max_length=100)),
            ],
            options={
                'verbose_name': 'Virtual Circuit',
                'verbose_name_plural': 'Virtual Circuits',
                'ordering': ['vcid'],
            },
        ),
        migrations.CreateModel(
            name='VirtualCircuitVLAN',
            fields=[
                ('created', models.DateField(auto_now_add=True, null=True)),
                ('last_updated', models.DateTimeField(auto_now=True, null=True)),
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('virtual_circuit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vlans', to='netbox_virtual_circuit_plugin.virtualcircuit')),
                ('vlan', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='virtual_circuit', to='ipam.vlan')),
            ],
            options={
                'verbose_name': 'Virtual-Circuit-to-VLAN connection',
                'verbose_name_plural': 'Virtual-Circuit-to-VLAN connections',
                'ordering': ['virtual_circuit'],
            },
        ),
    ]
