# Generated by Django 3.2.5 on 2021-08-19 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('netbox_virtual_circuit_plugin', '0001_initial'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='virtualcircuit',
            constraint=models.UniqueConstraint(fields=('vcid',), name='unique_vcid'),
        ),
    ]
